//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace CSSTC1 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.Bookmark 代码行数;
        
        internal Microsoft.Office.Tools.Word.Bookmark 偏离联系时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 偏离问题;
        
        internal Microsoft.Office.Tools.Word.Bookmark 填表时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 委托方单位;
        
        internal Microsoft.Office.Tools.Word.Bookmark 委托方姓名;
        
        internal Microsoft.Office.Tools.Word.Bookmark 委托方电话;
        
        internal Microsoft.Office.Tools.Word.Bookmark 年份;
        
        internal Microsoft.Office.Tools.Word.Bookmark 开发单位;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试依据;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试类型;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试类型个数;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试级别;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试组成员;
        
        internal Microsoft.Office.Tools.Word.Bookmark 测试阶段;
        
        internal Microsoft.Office.Tools.Word.Bookmark 系统_软件_开发单位;
        
        internal Microsoft.Office.Tools.Word.Bookmark 联系时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 被测件接收时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 被测件文档清单;
        
        internal Microsoft.Office.Tools.Word.Bookmark 被测件清单;
        
        internal Microsoft.Office.Tools.Word.Bookmark 被测件清单1;
        
        internal Microsoft.Office.Tools.Word.Bookmark 被测件编号;
        
        internal Microsoft.Office.Tools.Word.Bookmark 评审组成员;
        
        internal Microsoft.Office.Tools.Word.Bookmark 质量保证人员;
        
        internal Microsoft.Office.Tools.Word.Bookmark 软件名称;
        
        internal Microsoft.Office.Tools.Word.Bookmark 软件测试任务通知单;
        
        internal Microsoft.Office.Tools.Word.Bookmark 运行环境;
        
        internal Microsoft.Office.Tools.Word.Bookmark 项目名称;
        
        internal Microsoft.Office.Tools.Word.Bookmark 项目开始时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 项目标识;
        
        internal Microsoft.Office.Tools.Word.Bookmark 项目结束时间;
        
        internal Microsoft.Office.Tools.Word.Bookmark 项目负责人;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl2;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl3;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl4;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl5;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl6;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl7;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl8;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl9;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl10;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl11;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl12;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl13;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl14;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl15;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl16;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl17;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl18;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl19;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl20;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl21;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl22;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl23;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl24;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl25;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl26;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl27;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl28;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl PzControl0;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl52;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl53;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl54;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl55;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl56;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl57;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl58;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl59;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl60;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl61;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl62;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl63;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl64;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl65;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl66;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl67;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl68;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl69;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl70;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl71;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl72;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl73;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl74;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl75;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl76;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl77;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl78;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl79;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl80;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl81;
        
        internal Microsoft.Office.Tools.Word.Bookmark 文档审查;
        
        internal Microsoft.Office.Tools.Word.Bookmark 静态分析;
        
        internal Microsoft.Office.Tools.Word.Bookmark 功能测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 性能测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 强度测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 接口测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 可靠性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 边界测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 安全性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 人机交互界面测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 代码走查;
        
        internal Microsoft.Office.Tools.Word.Bookmark 容量测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 余量测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 安装性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 恢复性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 敏感性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 互操作性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 兼容性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 标准符合性测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 数据处理测试;
        
        internal Microsoft.Office.Tools.Word.Bookmark 内存使用缺陷;
        
        internal Microsoft.Office.Tools.Word.Bookmark 逻辑测试;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.代码行数.BeginInit();
            this.偏离联系时间.BeginInit();
            this.偏离问题.BeginInit();
            this.填表时间.BeginInit();
            this.委托方单位.BeginInit();
            this.委托方姓名.BeginInit();
            this.委托方电话.BeginInit();
            this.年份.BeginInit();
            this.开发单位.BeginInit();
            this.测试依据.BeginInit();
            this.测试类型.BeginInit();
            this.测试类型个数.BeginInit();
            this.测试级别.BeginInit();
            this.测试组成员.BeginInit();
            this.测试阶段.BeginInit();
            this.系统_软件_开发单位.BeginInit();
            this.联系时间.BeginInit();
            this.被测件接收时间.BeginInit();
            this.被测件文档清单.BeginInit();
            this.被测件清单.BeginInit();
            this.被测件清单1.BeginInit();
            this.被测件编号.BeginInit();
            this.评审组成员.BeginInit();
            this.质量保证人员.BeginInit();
            this.软件名称.BeginInit();
            this.软件测试任务通知单.BeginInit();
            this.运行环境.BeginInit();
            this.项目名称.BeginInit();
            this.项目开始时间.BeginInit();
            this.项目标识.BeginInit();
            this.项目结束时间.BeginInit();
            this.项目负责人.BeginInit();
            this.plainTextContentControl1.BeginInit();
            this.plainTextContentControl2.BeginInit();
            this.plainTextContentControl3.BeginInit();
            this.plainTextContentControl4.BeginInit();
            this.plainTextContentControl5.BeginInit();
            this.plainTextContentControl6.BeginInit();
            this.plainTextContentControl7.BeginInit();
            this.plainTextContentControl8.BeginInit();
            this.plainTextContentControl9.BeginInit();
            this.plainTextContentControl10.BeginInit();
            this.plainTextContentControl11.BeginInit();
            this.plainTextContentControl12.BeginInit();
            this.plainTextContentControl13.BeginInit();
            this.plainTextContentControl14.BeginInit();
            this.plainTextContentControl15.BeginInit();
            this.plainTextContentControl16.BeginInit();
            this.plainTextContentControl17.BeginInit();
            this.plainTextContentControl18.BeginInit();
            this.plainTextContentControl19.BeginInit();
            this.plainTextContentControl20.BeginInit();
            this.plainTextContentControl21.BeginInit();
            this.plainTextContentControl22.BeginInit();
            this.plainTextContentControl23.BeginInit();
            this.plainTextContentControl24.BeginInit();
            this.plainTextContentControl25.BeginInit();
            this.plainTextContentControl26.BeginInit();
            this.plainTextContentControl27.BeginInit();
            this.plainTextContentControl28.BeginInit();
            this.PzControl0.BeginInit();
            this.plainTextContentControl52.BeginInit();
            this.plainTextContentControl53.BeginInit();
            this.plainTextContentControl54.BeginInit();
            this.plainTextContentControl55.BeginInit();
            this.plainTextContentControl56.BeginInit();
            this.plainTextContentControl57.BeginInit();
            this.plainTextContentControl58.BeginInit();
            this.plainTextContentControl59.BeginInit();
            this.plainTextContentControl60.BeginInit();
            this.plainTextContentControl61.BeginInit();
            this.plainTextContentControl62.BeginInit();
            this.plainTextContentControl63.BeginInit();
            this.plainTextContentControl64.BeginInit();
            this.plainTextContentControl65.BeginInit();
            this.plainTextContentControl66.BeginInit();
            this.plainTextContentControl67.BeginInit();
            this.plainTextContentControl68.BeginInit();
            this.plainTextContentControl69.BeginInit();
            this.plainTextContentControl70.BeginInit();
            this.plainTextContentControl71.BeginInit();
            this.plainTextContentControl72.BeginInit();
            this.plainTextContentControl73.BeginInit();
            this.plainTextContentControl74.BeginInit();
            this.plainTextContentControl75.BeginInit();
            this.plainTextContentControl76.BeginInit();
            this.plainTextContentControl77.BeginInit();
            this.plainTextContentControl78.BeginInit();
            this.plainTextContentControl79.BeginInit();
            this.plainTextContentControl80.BeginInit();
            this.plainTextContentControl81.BeginInit();
            this.文档审查.BeginInit();
            this.静态分析.BeginInit();
            this.功能测试.BeginInit();
            this.性能测试.BeginInit();
            this.强度测试.BeginInit();
            this.接口测试.BeginInit();
            this.可靠性测试.BeginInit();
            this.边界测试.BeginInit();
            this.安全性测试.BeginInit();
            this.人机交互界面测试.BeginInit();
            this.代码走查.BeginInit();
            this.容量测试.BeginInit();
            this.余量测试.BeginInit();
            this.安装性测试.BeginInit();
            this.恢复性测试.BeginInit();
            this.敏感性测试.BeginInit();
            this.互操作性测试.BeginInit();
            this.兼容性测试.BeginInit();
            this.标准符合性测试.BeginInit();
            this.数据处理测试.BeginInit();
            this.内存使用缺陷.BeginInit();
            this.逻辑测试.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.逻辑测试.EndInit();
            this.内存使用缺陷.EndInit();
            this.数据处理测试.EndInit();
            this.标准符合性测试.EndInit();
            this.兼容性测试.EndInit();
            this.互操作性测试.EndInit();
            this.敏感性测试.EndInit();
            this.恢复性测试.EndInit();
            this.安装性测试.EndInit();
            this.余量测试.EndInit();
            this.容量测试.EndInit();
            this.代码走查.EndInit();
            this.人机交互界面测试.EndInit();
            this.安全性测试.EndInit();
            this.边界测试.EndInit();
            this.可靠性测试.EndInit();
            this.接口测试.EndInit();
            this.强度测试.EndInit();
            this.性能测试.EndInit();
            this.功能测试.EndInit();
            this.静态分析.EndInit();
            this.文档审查.EndInit();
            this.plainTextContentControl81.EndInit();
            this.plainTextContentControl80.EndInit();
            this.plainTextContentControl79.EndInit();
            this.plainTextContentControl78.EndInit();
            this.plainTextContentControl77.EndInit();
            this.plainTextContentControl76.EndInit();
            this.plainTextContentControl75.EndInit();
            this.plainTextContentControl74.EndInit();
            this.plainTextContentControl73.EndInit();
            this.plainTextContentControl72.EndInit();
            this.plainTextContentControl71.EndInit();
            this.plainTextContentControl70.EndInit();
            this.plainTextContentControl69.EndInit();
            this.plainTextContentControl68.EndInit();
            this.plainTextContentControl67.EndInit();
            this.plainTextContentControl66.EndInit();
            this.plainTextContentControl65.EndInit();
            this.plainTextContentControl64.EndInit();
            this.plainTextContentControl63.EndInit();
            this.plainTextContentControl62.EndInit();
            this.plainTextContentControl61.EndInit();
            this.plainTextContentControl60.EndInit();
            this.plainTextContentControl59.EndInit();
            this.plainTextContentControl58.EndInit();
            this.plainTextContentControl57.EndInit();
            this.plainTextContentControl56.EndInit();
            this.plainTextContentControl55.EndInit();
            this.plainTextContentControl54.EndInit();
            this.plainTextContentControl53.EndInit();
            this.plainTextContentControl52.EndInit();
            this.PzControl0.EndInit();
            this.plainTextContentControl28.EndInit();
            this.plainTextContentControl27.EndInit();
            this.plainTextContentControl26.EndInit();
            this.plainTextContentControl25.EndInit();
            this.plainTextContentControl24.EndInit();
            this.plainTextContentControl23.EndInit();
            this.plainTextContentControl22.EndInit();
            this.plainTextContentControl21.EndInit();
            this.plainTextContentControl20.EndInit();
            this.plainTextContentControl19.EndInit();
            this.plainTextContentControl18.EndInit();
            this.plainTextContentControl17.EndInit();
            this.plainTextContentControl16.EndInit();
            this.plainTextContentControl15.EndInit();
            this.plainTextContentControl14.EndInit();
            this.plainTextContentControl13.EndInit();
            this.plainTextContentControl12.EndInit();
            this.plainTextContentControl11.EndInit();
            this.plainTextContentControl10.EndInit();
            this.plainTextContentControl9.EndInit();
            this.plainTextContentControl8.EndInit();
            this.plainTextContentControl7.EndInit();
            this.plainTextContentControl6.EndInit();
            this.plainTextContentControl5.EndInit();
            this.plainTextContentControl4.EndInit();
            this.plainTextContentControl3.EndInit();
            this.plainTextContentControl2.EndInit();
            this.plainTextContentControl1.EndInit();
            this.项目负责人.EndInit();
            this.项目结束时间.EndInit();
            this.项目标识.EndInit();
            this.项目开始时间.EndInit();
            this.项目名称.EndInit();
            this.运行环境.EndInit();
            this.软件测试任务通知单.EndInit();
            this.软件名称.EndInit();
            this.质量保证人员.EndInit();
            this.评审组成员.EndInit();
            this.被测件编号.EndInit();
            this.被测件清单1.EndInit();
            this.被测件清单.EndInit();
            this.被测件文档清单.EndInit();
            this.被测件接收时间.EndInit();
            this.联系时间.EndInit();
            this.系统_软件_开发单位.EndInit();
            this.测试阶段.EndInit();
            this.测试组成员.EndInit();
            this.测试级别.EndInit();
            this.测试类型个数.EndInit();
            this.测试类型.EndInit();
            this.测试依据.EndInit();
            this.开发单位.EndInit();
            this.年份.EndInit();
            this.委托方电话.EndInit();
            this.委托方姓名.EndInit();
            this.委托方单位.EndInit();
            this.填表时间.EndInit();
            this.偏离问题.EndInit();
            this.偏离联系时间.EndInit();
            this.代码行数.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.代码行数 = Globals.Factory.CreateBookmark(null, null, "代码行数", "代码行数", this);
            this.偏离联系时间 = Globals.Factory.CreateBookmark(null, null, "偏离联系时间", "偏离联系时间", this);
            this.偏离问题 = Globals.Factory.CreateBookmark(null, null, "偏离问题", "偏离问题", this);
            this.填表时间 = Globals.Factory.CreateBookmark(null, null, "填表时间", "填表时间", this);
            this.委托方单位 = Globals.Factory.CreateBookmark(null, null, "委托方单位", "委托方单位", this);
            this.委托方姓名 = Globals.Factory.CreateBookmark(null, null, "委托方姓名", "委托方姓名", this);
            this.委托方电话 = Globals.Factory.CreateBookmark(null, null, "委托方电话", "委托方电话", this);
            this.年份 = Globals.Factory.CreateBookmark(null, null, "年份", "年份", this);
            this.开发单位 = Globals.Factory.CreateBookmark(null, null, "开发单位", "开发单位", this);
            this.测试依据 = Globals.Factory.CreateBookmark(null, null, "测试依据", "测试依据", this);
            this.测试类型 = Globals.Factory.CreateBookmark(null, null, "测试类型", "测试类型", this);
            this.测试类型个数 = Globals.Factory.CreateBookmark(null, null, "测试类型个数", "测试类型个数", this);
            this.测试级别 = Globals.Factory.CreateBookmark(null, null, "测试级别", "测试级别", this);
            this.测试组成员 = Globals.Factory.CreateBookmark(null, null, "测试组成员", "测试组成员", this);
            this.测试阶段 = Globals.Factory.CreateBookmark(null, null, "测试阶段", "测试阶段", this);
            this.系统_软件_开发单位 = Globals.Factory.CreateBookmark(null, null, "系统（软件）开发单位", "系统_软件_开发单位", this);
            this.联系时间 = Globals.Factory.CreateBookmark(null, null, "联系时间", "联系时间", this);
            this.被测件接收时间 = Globals.Factory.CreateBookmark(null, null, "被测件接收时间", "被测件接收时间", this);
            this.被测件文档清单 = Globals.Factory.CreateBookmark(null, null, "被测件文档清单", "被测件文档清单", this);
            this.被测件清单 = Globals.Factory.CreateBookmark(null, null, "被测件清单", "被测件清单", this);
            this.被测件清单1 = Globals.Factory.CreateBookmark(null, null, "被测件清单1", "被测件清单1", this);
            this.被测件编号 = Globals.Factory.CreateBookmark(null, null, "被测件编号", "被测件编号", this);
            this.评审组成员 = Globals.Factory.CreateBookmark(null, null, "评审组成员", "评审组成员", this);
            this.质量保证人员 = Globals.Factory.CreateBookmark(null, null, "质量保证人员", "质量保证人员", this);
            this.软件名称 = Globals.Factory.CreateBookmark(null, null, "软件名称", "软件名称", this);
            this.软件测试任务通知单 = Globals.Factory.CreateBookmark(null, null, "软件测试任务通知单", "软件测试任务通知单", this);
            this.运行环境 = Globals.Factory.CreateBookmark(null, null, "运行环境", "运行环境", this);
            this.项目名称 = Globals.Factory.CreateBookmark(null, null, "项目名称", "项目名称", this);
            this.项目开始时间 = Globals.Factory.CreateBookmark(null, null, "项目开始时间", "项目开始时间", this);
            this.项目标识 = Globals.Factory.CreateBookmark(null, null, "项目标识", "项目标识", this);
            this.项目结束时间 = Globals.Factory.CreateBookmark(null, null, "项目结束时间", "项目结束时间", this);
            this.项目负责人 = Globals.Factory.CreateBookmark(null, null, "项目负责人", "项目负责人", this);
            this.plainTextContentControl1 = Globals.Factory.CreatePlainTextContentControl(null, null, "1034779149", "plainTextContentControl1", this);
            this.plainTextContentControl2 = Globals.Factory.CreatePlainTextContentControl(null, null, "1691953511", "plainTextContentControl2", this);
            this.plainTextContentControl3 = Globals.Factory.CreatePlainTextContentControl(null, null, "1130057094", "plainTextContentControl3", this);
            this.plainTextContentControl4 = Globals.Factory.CreatePlainTextContentControl(null, null, "813383931", "plainTextContentControl4", this);
            this.plainTextContentControl5 = Globals.Factory.CreatePlainTextContentControl(null, null, "3117389389", "plainTextContentControl5", this);
            this.plainTextContentControl6 = Globals.Factory.CreatePlainTextContentControl(null, null, "366880825", "plainTextContentControl6", this);
            this.plainTextContentControl7 = Globals.Factory.CreatePlainTextContentControl(null, null, "1336880818", "plainTextContentControl7", this);
            this.plainTextContentControl8 = Globals.Factory.CreatePlainTextContentControl(null, null, "3002611369", "plainTextContentControl8", this);
            this.plainTextContentControl9 = Globals.Factory.CreatePlainTextContentControl(null, null, "983514335", "plainTextContentControl9", this);
            this.plainTextContentControl10 = Globals.Factory.CreatePlainTextContentControl(null, null, "2438558683", "plainTextContentControl10", this);
            this.plainTextContentControl11 = Globals.Factory.CreatePlainTextContentControl(null, null, "1542558793", "plainTextContentControl11", this);
            this.plainTextContentControl12 = Globals.Factory.CreatePlainTextContentControl(null, null, "2264717304", "plainTextContentControl12", this);
            this.plainTextContentControl13 = Globals.Factory.CreatePlainTextContentControl(null, null, "2973542036", "plainTextContentControl13", this);
            this.plainTextContentControl14 = Globals.Factory.CreatePlainTextContentControl(null, null, "3699636150", "plainTextContentControl14", this);
            this.plainTextContentControl15 = Globals.Factory.CreatePlainTextContentControl(null, null, "1855925281", "plainTextContentControl15", this);
            this.plainTextContentControl16 = Globals.Factory.CreatePlainTextContentControl(null, null, "842050473", "plainTextContentControl16", this);
            this.plainTextContentControl17 = Globals.Factory.CreatePlainTextContentControl(null, null, "483588663", "plainTextContentControl17", this);
            this.plainTextContentControl18 = Globals.Factory.CreatePlainTextContentControl(null, null, "3354434976", "plainTextContentControl18", this);
            this.plainTextContentControl19 = Globals.Factory.CreatePlainTextContentControl(null, null, "3664560049", "plainTextContentControl19", this);
            this.plainTextContentControl20 = Globals.Factory.CreatePlainTextContentControl(null, null, "2995673922", "plainTextContentControl20", this);
            this.plainTextContentControl21 = Globals.Factory.CreatePlainTextContentControl(null, null, "3993653705", "plainTextContentControl21", this);
            this.plainTextContentControl22 = Globals.Factory.CreatePlainTextContentControl(null, null, "612552312", "plainTextContentControl22", this);
            this.plainTextContentControl23 = Globals.Factory.CreatePlainTextContentControl(null, null, "629674059", "plainTextContentControl23", this);
            this.plainTextContentControl24 = Globals.Factory.CreatePlainTextContentControl(null, null, "611174104", "plainTextContentControl24", this);
            this.plainTextContentControl25 = Globals.Factory.CreatePlainTextContentControl(null, null, "1493376098", "plainTextContentControl25", this);
            this.plainTextContentControl26 = Globals.Factory.CreatePlainTextContentControl(null, null, "8492335", "plainTextContentControl26", this);
            this.plainTextContentControl27 = Globals.Factory.CreatePlainTextContentControl(null, null, "959607605", "plainTextContentControl27", this);
            this.plainTextContentControl28 = Globals.Factory.CreatePlainTextContentControl(null, null, "3680828327", "plainTextContentControl28", this);
            this.PzControl0 = Globals.Factory.CreatePlainTextContentControl(null, null, "4024964752", "PzControl0", this);
            this.plainTextContentControl52 = Globals.Factory.CreatePlainTextContentControl(null, null, "3587868203", "plainTextContentControl52", this);
            this.plainTextContentControl53 = Globals.Factory.CreatePlainTextContentControl(null, null, "3038537754", "plainTextContentControl53", this);
            this.plainTextContentControl54 = Globals.Factory.CreatePlainTextContentControl(null, null, "1563675853", "plainTextContentControl54", this);
            this.plainTextContentControl55 = Globals.Factory.CreatePlainTextContentControl(null, null, "2264336184", "plainTextContentControl55", this);
            this.plainTextContentControl56 = Globals.Factory.CreatePlainTextContentControl(null, null, "273603492", "plainTextContentControl56", this);
            this.plainTextContentControl57 = Globals.Factory.CreatePlainTextContentControl(null, null, "149645482", "plainTextContentControl57", this);
            this.plainTextContentControl58 = Globals.Factory.CreatePlainTextContentControl(null, null, "1006866850", "plainTextContentControl58", this);
            this.plainTextContentControl59 = Globals.Factory.CreatePlainTextContentControl(null, null, "932402357", "plainTextContentControl59", this);
            this.plainTextContentControl60 = Globals.Factory.CreatePlainTextContentControl(null, null, "4219597018", "plainTextContentControl60", this);
            this.plainTextContentControl61 = Globals.Factory.CreatePlainTextContentControl(null, null, "3130033331", "plainTextContentControl61", this);
            this.plainTextContentControl62 = Globals.Factory.CreatePlainTextContentControl(null, null, "3920117779", "plainTextContentControl62", this);
            this.plainTextContentControl63 = Globals.Factory.CreatePlainTextContentControl(null, null, "1465779551", "plainTextContentControl63", this);
            this.plainTextContentControl64 = Globals.Factory.CreatePlainTextContentControl(null, null, "3848883976", "plainTextContentControl64", this);
            this.plainTextContentControl65 = Globals.Factory.CreatePlainTextContentControl(null, null, "3575451673", "plainTextContentControl65", this);
            this.plainTextContentControl66 = Globals.Factory.CreatePlainTextContentControl(null, null, "997539831", "plainTextContentControl66", this);
            this.plainTextContentControl67 = Globals.Factory.CreatePlainTextContentControl(null, null, "2453967640", "plainTextContentControl67", this);
            this.plainTextContentControl68 = Globals.Factory.CreatePlainTextContentControl(null, null, "2292771035", "plainTextContentControl68", this);
            this.plainTextContentControl69 = Globals.Factory.CreatePlainTextContentControl(null, null, "2261315916", "plainTextContentControl69", this);
            this.plainTextContentControl70 = Globals.Factory.CreatePlainTextContentControl(null, null, "1592970103", "plainTextContentControl70", this);
            this.plainTextContentControl71 = Globals.Factory.CreatePlainTextContentControl(null, null, "3380419259", "plainTextContentControl71", this);
            this.plainTextContentControl72 = Globals.Factory.CreatePlainTextContentControl(null, null, "471105146", "plainTextContentControl72", this);
            this.plainTextContentControl73 = Globals.Factory.CreatePlainTextContentControl(null, null, "1703207570", "plainTextContentControl73", this);
            this.plainTextContentControl74 = Globals.Factory.CreatePlainTextContentControl(null, null, "812602267", "plainTextContentControl74", this);
            this.plainTextContentControl75 = Globals.Factory.CreatePlainTextContentControl(null, null, "3485336458", "plainTextContentControl75", this);
            this.plainTextContentControl76 = Globals.Factory.CreatePlainTextContentControl(null, null, "4109677574", "plainTextContentControl76", this);
            this.plainTextContentControl77 = Globals.Factory.CreatePlainTextContentControl(null, null, "3824906072", "plainTextContentControl77", this);
            this.plainTextContentControl78 = Globals.Factory.CreatePlainTextContentControl(null, null, "1641529612", "plainTextContentControl78", this);
            this.plainTextContentControl79 = Globals.Factory.CreatePlainTextContentControl(null, null, "3556952283", "plainTextContentControl79", this);
            this.plainTextContentControl80 = Globals.Factory.CreatePlainTextContentControl(null, null, "238214948", "plainTextContentControl80", this);
            this.plainTextContentControl81 = Globals.Factory.CreatePlainTextContentControl(null, null, "3248448644", "plainTextContentControl81", this);
            this.文档审查 = Globals.Factory.CreateBookmark(null, null, "文档审查", "文档审查", this);
            this.静态分析 = Globals.Factory.CreateBookmark(null, null, "静态分析", "静态分析", this);
            this.功能测试 = Globals.Factory.CreateBookmark(null, null, "功能测试", "功能测试", this);
            this.性能测试 = Globals.Factory.CreateBookmark(null, null, "性能测试", "性能测试", this);
            this.强度测试 = Globals.Factory.CreateBookmark(null, null, "强度测试", "强度测试", this);
            this.接口测试 = Globals.Factory.CreateBookmark(null, null, "接口测试", "接口测试", this);
            this.可靠性测试 = Globals.Factory.CreateBookmark(null, null, "可靠性测试", "可靠性测试", this);
            this.边界测试 = Globals.Factory.CreateBookmark(null, null, "边界测试", "边界测试", this);
            this.安全性测试 = Globals.Factory.CreateBookmark(null, null, "安全性测试", "安全性测试", this);
            this.人机交互界面测试 = Globals.Factory.CreateBookmark(null, null, "人机交互界面测试", "人机交互界面测试", this);
            this.代码走查 = Globals.Factory.CreateBookmark(null, null, "代码走查", "代码走查", this);
            this.容量测试 = Globals.Factory.CreateBookmark(null, null, "容量测试", "容量测试", this);
            this.余量测试 = Globals.Factory.CreateBookmark(null, null, "余量测试", "余量测试", this);
            this.安装性测试 = Globals.Factory.CreateBookmark(null, null, "安装性测试", "安装性测试", this);
            this.恢复性测试 = Globals.Factory.CreateBookmark(null, null, "恢复性测试", "恢复性测试", this);
            this.敏感性测试 = Globals.Factory.CreateBookmark(null, null, "敏感性测试", "敏感性测试", this);
            this.互操作性测试 = Globals.Factory.CreateBookmark(null, null, "互操作性测试", "互操作性测试", this);
            this.兼容性测试 = Globals.Factory.CreateBookmark(null, null, "兼容性测试", "兼容性测试", this);
            this.标准符合性测试 = Globals.Factory.CreateBookmark(null, null, "标准符合性测试", "标准符合性测试", this);
            this.数据处理测试 = Globals.Factory.CreateBookmark(null, null, "数据处理测试", "数据处理测试", this);
            this.内存使用缺陷 = Globals.Factory.CreateBookmark(null, null, "内存使用缺陷", "内存使用缺陷", this);
            this.逻辑测试 = Globals.Factory.CreateBookmark(null, null, "逻辑测试", "逻辑测试", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // 代码行数
            // 
            this.代码行数.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 偏离联系时间
            // 
            this.偏离联系时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 偏离问题
            // 
            this.偏离问题.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 填表时间
            // 
            this.填表时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 委托方单位
            // 
            this.委托方单位.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 委托方姓名
            // 
            this.委托方姓名.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 委托方电话
            // 
            this.委托方电话.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 年份
            // 
            this.年份.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 开发单位
            // 
            this.开发单位.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试依据
            // 
            this.测试依据.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试类型
            // 
            this.测试类型.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试类型个数
            // 
            this.测试类型个数.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试级别
            // 
            this.测试级别.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试组成员
            // 
            this.测试组成员.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 测试阶段
            // 
            this.测试阶段.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 系统_软件_开发单位
            // 
            this.系统_软件_开发单位.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 联系时间
            // 
            this.联系时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 被测件接收时间
            // 
            this.被测件接收时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 被测件文档清单
            // 
            this.被测件文档清单.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 被测件清单
            // 
            this.被测件清单.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 被测件清单1
            // 
            this.被测件清单1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 被测件编号
            // 
            this.被测件编号.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 评审组成员
            // 
            this.评审组成员.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 质量保证人员
            // 
            this.质量保证人员.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 软件名称
            // 
            this.软件名称.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 软件测试任务通知单
            // 
            this.软件测试任务通知单.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 运行环境
            // 
            this.运行环境.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 项目名称
            // 
            this.项目名称.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 项目开始时间
            // 
            this.项目开始时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 项目标识
            // 
            this.项目标识.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 项目结束时间
            // 
            this.项目结束时间.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 项目负责人
            // 
            this.项目负责人.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl1
            // 
            this.plainTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl2
            // 
            this.plainTextContentControl2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl3
            // 
            this.plainTextContentControl3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl4
            // 
            this.plainTextContentControl4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl5
            // 
            this.plainTextContentControl5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl6
            // 
            this.plainTextContentControl6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl7
            // 
            this.plainTextContentControl7.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl8
            // 
            this.plainTextContentControl8.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl9
            // 
            this.plainTextContentControl9.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl10
            // 
            this.plainTextContentControl10.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl11
            // 
            this.plainTextContentControl11.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl12
            // 
            this.plainTextContentControl12.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl13
            // 
            this.plainTextContentControl13.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl14
            // 
            this.plainTextContentControl14.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl15
            // 
            this.plainTextContentControl15.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl16
            // 
            this.plainTextContentControl16.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl17
            // 
            this.plainTextContentControl17.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl18
            // 
            this.plainTextContentControl18.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl19
            // 
            this.plainTextContentControl19.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl20
            // 
            this.plainTextContentControl20.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl21
            // 
            this.plainTextContentControl21.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl22
            // 
            this.plainTextContentControl22.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl23
            // 
            this.plainTextContentControl23.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl24
            // 
            this.plainTextContentControl24.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl25
            // 
            this.plainTextContentControl25.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl26
            // 
            this.plainTextContentControl26.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl27
            // 
            this.plainTextContentControl27.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl28
            // 
            this.plainTextContentControl28.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // PzControl0
            // 
            this.PzControl0.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl52
            // 
            this.plainTextContentControl52.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl53
            // 
            this.plainTextContentControl53.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl54
            // 
            this.plainTextContentControl54.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl55
            // 
            this.plainTextContentControl55.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl56
            // 
            this.plainTextContentControl56.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl57
            // 
            this.plainTextContentControl57.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl58
            // 
            this.plainTextContentControl58.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl59
            // 
            this.plainTextContentControl59.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl60
            // 
            this.plainTextContentControl60.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl61
            // 
            this.plainTextContentControl61.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl62
            // 
            this.plainTextContentControl62.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl63
            // 
            this.plainTextContentControl63.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl64
            // 
            this.plainTextContentControl64.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl65
            // 
            this.plainTextContentControl65.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl66
            // 
            this.plainTextContentControl66.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl67
            // 
            this.plainTextContentControl67.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl68
            // 
            this.plainTextContentControl68.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl69
            // 
            this.plainTextContentControl69.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl70
            // 
            this.plainTextContentControl70.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl71
            // 
            this.plainTextContentControl71.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl72
            // 
            this.plainTextContentControl72.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl73
            // 
            this.plainTextContentControl73.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl74
            // 
            this.plainTextContentControl74.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl75
            // 
            this.plainTextContentControl75.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl76
            // 
            this.plainTextContentControl76.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl77
            // 
            this.plainTextContentControl77.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl78
            // 
            this.plainTextContentControl78.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl79
            // 
            this.plainTextContentControl79.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl80
            // 
            this.plainTextContentControl80.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl81
            // 
            this.plainTextContentControl81.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 文档审查
            // 
            this.文档审查.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 静态分析
            // 
            this.静态分析.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 功能测试
            // 
            this.功能测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 性能测试
            // 
            this.性能测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 强度测试
            // 
            this.强度测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 接口测试
            // 
            this.接口测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 可靠性测试
            // 
            this.可靠性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 边界测试
            // 
            this.边界测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 安全性测试
            // 
            this.安全性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 人机交互界面测试
            // 
            this.人机交互界面测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 代码走查
            // 
            this.代码走查.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 容量测试
            // 
            this.容量测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 余量测试
            // 
            this.余量测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 安装性测试
            // 
            this.安装性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 恢复性测试
            // 
            this.恢复性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 敏感性测试
            // 
            this.敏感性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 互操作性测试
            // 
            this.互操作性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 兼容性测试
            // 
            this.兼容性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 标准符合性测试
            // 
            this.标准符合性测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 数据处理测试
            // 
            this.数据处理测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 内存使用缺陷
            // 
            this.内存使用缺陷.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // 逻辑测试
            // 
            this.逻辑测试.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.逻辑测试.Dispose();
            this.内存使用缺陷.Dispose();
            this.数据处理测试.Dispose();
            this.标准符合性测试.Dispose();
            this.兼容性测试.Dispose();
            this.互操作性测试.Dispose();
            this.敏感性测试.Dispose();
            this.恢复性测试.Dispose();
            this.安装性测试.Dispose();
            this.余量测试.Dispose();
            this.容量测试.Dispose();
            this.代码走查.Dispose();
            this.人机交互界面测试.Dispose();
            this.安全性测试.Dispose();
            this.边界测试.Dispose();
            this.可靠性测试.Dispose();
            this.接口测试.Dispose();
            this.强度测试.Dispose();
            this.性能测试.Dispose();
            this.功能测试.Dispose();
            this.静态分析.Dispose();
            this.文档审查.Dispose();
            this.plainTextContentControl81.Dispose();
            this.plainTextContentControl80.Dispose();
            this.plainTextContentControl79.Dispose();
            this.plainTextContentControl78.Dispose();
            this.plainTextContentControl77.Dispose();
            this.plainTextContentControl76.Dispose();
            this.plainTextContentControl75.Dispose();
            this.plainTextContentControl74.Dispose();
            this.plainTextContentControl73.Dispose();
            this.plainTextContentControl72.Dispose();
            this.plainTextContentControl71.Dispose();
            this.plainTextContentControl70.Dispose();
            this.plainTextContentControl69.Dispose();
            this.plainTextContentControl68.Dispose();
            this.plainTextContentControl67.Dispose();
            this.plainTextContentControl66.Dispose();
            this.plainTextContentControl65.Dispose();
            this.plainTextContentControl64.Dispose();
            this.plainTextContentControl63.Dispose();
            this.plainTextContentControl62.Dispose();
            this.plainTextContentControl61.Dispose();
            this.plainTextContentControl60.Dispose();
            this.plainTextContentControl59.Dispose();
            this.plainTextContentControl58.Dispose();
            this.plainTextContentControl57.Dispose();
            this.plainTextContentControl56.Dispose();
            this.plainTextContentControl55.Dispose();
            this.plainTextContentControl54.Dispose();
            this.plainTextContentControl53.Dispose();
            this.plainTextContentControl52.Dispose();
            this.PzControl0.Dispose();
            this.plainTextContentControl28.Dispose();
            this.plainTextContentControl27.Dispose();
            this.plainTextContentControl26.Dispose();
            this.plainTextContentControl25.Dispose();
            this.plainTextContentControl24.Dispose();
            this.plainTextContentControl23.Dispose();
            this.plainTextContentControl22.Dispose();
            this.plainTextContentControl21.Dispose();
            this.plainTextContentControl20.Dispose();
            this.plainTextContentControl19.Dispose();
            this.plainTextContentControl18.Dispose();
            this.plainTextContentControl17.Dispose();
            this.plainTextContentControl16.Dispose();
            this.plainTextContentControl15.Dispose();
            this.plainTextContentControl14.Dispose();
            this.plainTextContentControl13.Dispose();
            this.plainTextContentControl12.Dispose();
            this.plainTextContentControl11.Dispose();
            this.plainTextContentControl10.Dispose();
            this.plainTextContentControl9.Dispose();
            this.plainTextContentControl8.Dispose();
            this.plainTextContentControl7.Dispose();
            this.plainTextContentControl6.Dispose();
            this.plainTextContentControl5.Dispose();
            this.plainTextContentControl4.Dispose();
            this.plainTextContentControl3.Dispose();
            this.plainTextContentControl2.Dispose();
            this.plainTextContentControl1.Dispose();
            this.项目负责人.Dispose();
            this.项目结束时间.Dispose();
            this.项目标识.Dispose();
            this.项目开始时间.Dispose();
            this.项目名称.Dispose();
            this.运行环境.Dispose();
            this.软件测试任务通知单.Dispose();
            this.软件名称.Dispose();
            this.质量保证人员.Dispose();
            this.评审组成员.Dispose();
            this.被测件编号.Dispose();
            this.被测件清单1.Dispose();
            this.被测件清单.Dispose();
            this.被测件文档清单.Dispose();
            this.被测件接收时间.Dispose();
            this.联系时间.Dispose();
            this.系统_软件_开发单位.Dispose();
            this.测试阶段.Dispose();
            this.测试组成员.Dispose();
            this.测试级别.Dispose();
            this.测试类型个数.Dispose();
            this.测试类型.Dispose();
            this.测试依据.Dispose();
            this.开发单位.Dispose();
            this.年份.Dispose();
            this.委托方电话.Dispose();
            this.委托方姓名.Dispose();
            this.委托方单位.Dispose();
            this.填表时间.Dispose();
            this.偏离问题.Dispose();
            this.偏离联系时间.Dispose();
            this.代码行数.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
